#!/usr/bin/env bash
# IsoFLOP PR-2 smoke skeleton — DO NOT EXECUTE without holding a node.
#
# Four smokes:
#   1. plan      (no compute)            — assert 5 cells emitted
#   2. print     (no compute)            — show launcher cmds
#   3. dry-run   (no compute, qsub.sh)   — assert qsub scripts generated
#   4. end-to-end loop closure (1N debug, ~10-15 min) — full plan/launch/
#      collect/fit round trip on a single budget × 5 variants.
#
# This script is intentionally NOT auto-runnable: each smoke needs a node
# hold (for smoke 4) or just a venv-active shell (smokes 1-3). Mirrors the
# tools/parity/*.sh convention.

set -euo pipefail

cat <<'NOTE'
================================================================
IsoFLOP PR-2 smoke skeleton — manual execution only.

Prereqs:
  - PR-1 merged on main
  - 5 calibration JSONs under <scaling-study-dir>/calibration/ for
    OLMo-3 1B × {BASE, W2X, W4X, D2X, D4X} on text_image. Generated by
    PR-1 Smoke 2.
================================================================
NOTE

cat <<'SMOKE1'
================================================================
[Smoke 1] plan (no compute, < 1 sec)

python tools/isoflop_plan.py \
  --family text_image \
  --budgets 3e17 \
  --backbones OLMO3-1B \
  --projector-variants BASE,W2X,W4X,D2X,D4X \
  --calibration-dir /flare/ModCon/ngetty/BaseMM_PRISM/scaling-study/calibration/ \
  --output /tmp/iso-plan-smoke.yaml

Pass criteria:
  - 5 entries under cells:
  - every cell has status: planned
  - every cell has max_steps > 0
  - calibration_json paths resolve to existing files
================================================================
SMOKE1

cat <<'SMOKE2'
================================================================
[Smoke 2] print mode (no compute, < 1 sec)

python tools/isoflop_launch.py --plan /tmp/iso-plan-smoke.yaml --print

Pass criteria:
  - 5 python tools/launch_aurora_daos.py ... lines on stdout
  - each contains --target-flops 3.000000e+17
  - each contains --calibration-json /flare/.../calibration/OLMO3-1B-*.json
  - each contains one of BASE/W2X/W4X/D2X/D4X in --id
  - no CSV written (experiments.csv untouched)
================================================================
SMOKE2

cat <<'SMOKE3'
================================================================
[Smoke 3] dry-run launch (no compute, generates qsub.sh)

python tools/isoflop_launch.py \
  --plan /tmp/iso-plan-smoke.yaml \
  --csv /tmp/iso-smoke-experiments.csv \
  --dry-run

Pass criteria:
  - jobs/run_aurora_daos_*.sh exists for all 5 variants
  - each qsub script contains --target-flops
  - each qsub script contains model.projector_hidden_mult=
  - /tmp/iso-smoke-experiments.csv has 5 rows with status=planned
    (dry-run does NOT flip to running, so a real launch later picks
    them up; only a real submit flips to running)
================================================================
SMOKE3

cat <<'SMOKE4'
================================================================
[Smoke 4] end-to-end loop closure (1N debug, ~10-15 min)

# Hold a node first:
qsub -I -l select=1:system=aurora,walltime=01:00:00 -q debug -A ModCon

# In the held shell, activate env, then:
python tools/isoflop_launch.py --plan /tmp/iso-plan-smoke.yaml \
  --csv /tmp/iso-smoke-experiments.csv

# After all 5 cells complete (~10-15 min total):
python tools/isoflop_collect.py \
  --outputs outputs/ \
  --csv /tmp/iso-smoke-experiments.csv

python tools/isoflop_fit.py \
  --csv /tmp/iso-smoke-experiments.csv \
  --family text_image --backbone OLMO3-1B \
  --bootstrap 100 \
  --output-json /tmp/iso-fit-smoke.json \
  --output-md   /tmp/iso-fit-smoke.md

Pass criteria:
  - 5 CSV rows flipped to status=done
  - n_total_params, flops_per_step, samples_per_sec, loss_main populated
    for each
  - fit JSON contains a parabola with non-NaN N_opt
    (α/β not meaningful at 1 budget — smoke validates the loop, not
    the actual scaling fit)
================================================================
SMOKE4
